apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
  labels:
    app: item-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
        - name: item-service
          image: docker.io/nisal1232/item-service:latest
          ports:
            - containerPort: 8003
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: item-service
spec:
  selector:
    app: item-service
  type: LoadBalancer
  ports:
    - port: 8003
